import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TrpcProvider } from '@/components/providers/trpc-provider';
import { Toaster } from '@/components/ui/sonner';
import { dark } from '@clerk/themes';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/components/providers/theme-provider';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" style={{ colorScheme: 'dark' }} className="dark">
        <TrpcProvider>
          <body className={inter.className}>
            <ThemeProvider attribute="class" storageKey="pinnacle-theme">
              <Toaster position="bottom-center" />
              {children}
            </ThemeProvider>
          </body>
        </TrpcProvider>
      </html>
    </ClerkProvider>
  );
}
